using System;

namespace CNCEmu.Services.Logger
{
    [Flags]
    public enum LogType
    {
        None = 0,

        /// <summary>
        /// Info: General information about the application’s operation.
        /// </summary>
        INFO = 1,

        /// <summary>
        /// Warning : Indications of potential issues or important events that are not errors.
        /// </summary>
        WARN = 2,

        /// <summary>
        /// Error : Errors that occur during the application’s execution.
        /// </summary>
        ERRR = 4,

        /// <summary>
        /// Debug : Detailed information used for debugging purposes.
        /// </summary>
        DEBG = 8,

        /// <summary>
        /// Trace : Granular information to trace the execution flow of the application.
        /// </summary>
        TRCE = 16,

        /// <summary>
        /// Audit : Records of user actions and changes to data for security and compliance.
        /// </summary>
        AUDT = 32,

        /// <summary>
        /// Transaction : Logs of database transactions for recovery and consistency.
        /// </summary>
        TRAN = 64,

        /// <summary>
        /// Event : Logs of significant events within the system, such as startup and shutdown.
        /// </summary>
        EVNT = 128,

        /// <summary>
        /// Security : Logs related to security events, such as login attempts and access control violations.
        /// </summary>
        SECU = 256,

        /// <summary>
        /// Application : Logs specific to an application’s behavior and performance.
        /// </summary>
        APPL = 512,

        /// <summary>
        /// System : Logs generated by the operating system, capturing system-level events and errors.
        /// </summary>
        SYST = 1024,
    }
}
